#!/bin/bash
#Script by : PR Aiman
clear
MYIP=$(wget -qO- ipv4.icanhazip.com)
User=trial`</dev/urandom tr -dc X-Z0-9 | head -c4`
Pass=`</dev/urandom tr -dc a-f0-9 | head -c9`
echo ""
read -p " Active Days : " Days
echo ""
Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d-%m-%Y')
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
privoxyport="$(netstat -nlpt | grep -i privoxy | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
squidport="$(netstat -nlpt | grep -i squid | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
useradd -e `date -d "$Days days" +"%Y-%m-%d"` -s /bin/false -M $User
echo -e "$Pass\n$Pass\n"|passwd $User &> /dev/null
clear
echo ""
echo -e "\e[1;31m [*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;37m                AutoScriptVPN by PR Aiman"
echo -e "\e[0m                                                   "
echo -e "\e[0;37m Username : $User"
echo -e "\e[0;37m Password : $Pass"
echo -e "\e[0;37m Time Active : $Days Days"
echo -e "\e[0;37m Expired Date : $Expiration_Display"
echo -e "\e[0m                                                   "	
echo -e "\e[0;37m Host / IP : "$MYIP
echo -e "\e[0;37m Port OpenSSH : "$opensshport
echo -e "\e[0;37m Port Dropbear : "$dropbearport
echo -e "\e[0;37m Port SSL : "$stunnel4port
echo -e "\e[0;37m Port Privoxy : "$privoxyport
echo -e "\e[0;37m Port Squid : "$squidport
echo -e "\e[0;37m Port OpenVPN : "$openvpnport
echo -e "\e[0;37m Download Config : http://$MYIP:85"
echo -e "                                                  "
echo -e "\e[1;31m [*][*][*]======================================[*][*][*]"
echo ""
read -sp " Press ENTER to go back"
echo ""
menu
