#!/bin/bash
# Script by : PR Aiman

clear
echo -e "\e[0m                                                   "
echo -e "\e[1;31m     [*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;37m                    AutoScriptVPN by  PR Aiman           "
echo -e "\e[0m                                                   "
echo -e "\e[0;37m                    [1] Show All Service Ports"
echo -e "\e[0;37m                    [2] Edit Port OpenSSH"
echo -e "\e[0;37m                    [3] Edit Port Dropbear"
echo -e "\e[0;37m                    [4] Edit Port Stunnel"
echo -e "\e[0;37m                    [5] Edit Port OpenVPN"
echo -e "\e[0;37m                    [6] Edit Port Squid"
echo -e "\e[0;37m                    [7] Back"
echo -e "\e[0;37m                    [x] Exit"
echo -e "\e[0m                                                   "
read -p "              Select From Options [1-7 or x] : " Port
echo -e "\e[0m                                                   "
echo -e "\e[1;31m     [*][*][*]======================================[*][*][*]"
clear
case $Port in
			1)
			clear
			show_ports
			exit
			;;
			2)
			clear
			edit_openssh
			exit
			;;
			3)
			clear
			edit_dropbear
			exit
			;;
			4)
			clear
			edit_stunnel4
			exit
			;;
			5)
			clear
			edit_openvpn
			exit
			;;
			6)
			clear
			edit_squid3
			exit
			;;
			7)
			clear
			options
			exit
			;;
			x)
			clear
			exit
			;;
			*)
            edit_ports
		    ;;
	esac