#!/bin/bash
#Licensed to https://www.hostingtermurah.net/
#Script by PR Aiman

MYIP=$(wget -qO- ipv4.icanhazip.com)
if [ $MYIP = "" ]; then
   MYIP=`ifconfig | grep 'inet addr:' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d: -f2 | awk '{ print $1}' | head -1`;
fi
echo " "
echo "==========================================="
echo "DEFAULT INSTALLATION DETAILS"
echo "==========================================="
echo "" 
echo "-------"
echo "SERVICE" 
echo "-------"  
echo "OpenVPN     : TCP 1194"  
echo "OpenVPN SSL : TCP 443"  
echo "OpenSSH     : 22, 110, 90"  
echo "Stunnel4    : 444"
echo "Dropbear    : 442"  
echo "Squid3      : 3128, 8080 (limit to IP VPS)"  
echo "PPTP VPN    : 1723" 
echo "Badvpn      : badvpn-udpgw port 7300"  
echo "Nginx       : 80"  
echo "Configs     : http://$MYIP/configs.zip)"
echo ""  
echo "-----"
echo "TOOLS"  
echo "-----" 
echo "axel"  
echo "bmon"  
echo "htop"  
echo "iftop"  
echo "mtr"  
echo "" 
echo "------"
echo "SCRIPT"  
echo "------" 
echo "√ Premium Script installed on your server!" 
echo "~ Type premium-script to display the menu"
echo ""  
echo "--------------"
echo "OTHER FEATURES" 
echo "--------------"  
echo "Webmin   : http://$MYIP:10000/"  
echo "vnstat   : http://$MYIP/vnstat/"  
echo "MRTG     : http://$MYIP/mrtg/"  
echo "Timezone : Asia/Manila"  
echo "Fail2Ban : [ON]"  
echo "DDflate  : [ON]"
echo "IPv6     : [OFF]"  
echo "" 
echo "==========================================="
echo "---------- Created by PR Aiman ----------"
echo "-------------------------------------------"
echo " "