#!/bin/bash
# Script by : PR Aiman

clear
echo -e "\e[0m                                                   "
echo -e "\e[1;31m     [*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;37m                    AutoScriptVPN by PR Aiman   "
echo -e "\e[0m                                                   "
echo -e "\e[0;37m                    [1] Reboot Now"
echo -e "\e[0;37m                    [2] Set Reboot Time"
echo -e "\e[0;37m                    [3] Back"
echo -e "\e[0;37m                    [x] Exit"
echo -e "\e[0m                                                   "
read -p "              Select From Options [1-3 or x] :  " Reboot
echo -e "\e[0m                                                   "
echo -e "\e[1;31m     [*][*][*]======================================[*][*][*]"
clear
case $Reboot in
		1)
		clear
		reboot
		exit
		;;
		2)
		clear
		reboot_sys_auto
		exit
		;;
		3)
		clear
		options
		exit
		;;
		x)
		clear
		exit
		;;
		*)
        reboot_sys
		;;
	esac