#!/bin/bash
# Script by : PR Aiman
clear
echo -e "\e[0m                                                   "
echo -e "\e[1;31m     [*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;37m                    AutoScriptVPN by PR Aiman"
echo -e "\e[0m                                                   "
read -p "                  Username : " User
egrep "^$User" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
read -p "                  Day Extend : " Days
Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
passwd -u $User
usermod -e  $Expiration $User
egrep "^$User" /etc/passwd >/dev/null
echo -e "$Pass\n$Pass\n"|passwd $User &> /dev/null
clear
echo -e "\e[0m                                                   "
echo -e "\e[1;31m [*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;37m                AutoScriptVPN by PR Aiman"
echo -e "\e[0m                                                   "
echo -e "\e[0;37m Username : $User"
echo -e "\e[0;37m Days Extend : $Days Days"
echo -e "\e[0;37m Expired Date : $Expiration_Display"
echo -e "\e[0m                                                   "
echo -e "\e[1;31m [*][*][*]======================================[*][*][*]"
echo ""
read -sp " Press ENTER to go back"
echo ""
options
else
clear
echo -e "\e[0m                                                   "
echo -e "\e[1;31m     [*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;37m                    AutoScriptVPN by PR Aiman"
echo -e "\e[0m                                                   "
echo -e "\e[1;31m                    Username Doesnt Exist               "
echo -e "\e[0m                                                   "
echo -e "\e[1;31m     [*][*][*]======================================[*][*][*]"
echo ""
read -sp " Press ENTER to go back"
echo ""
menu
fi