#!/bin/bash
#Script by : PR Aiman
versi=$(cat /home/ver)
if [[ $versi == 1.6 ]]; then
echo ""
echo -e "\e[1;31m  You Already The Latest Version"
echo ""
exit 0
fi
echo -e "\e[0;37m  Update will be begin..."
# Update Script
cd /usr/local/sbin/
wget -O bench-network "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/bench-network"
wget -O connections "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/connections"
wget -O create "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/create"
wget -O create_trial "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/create_trial"
wget -O delete_expired "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/delete_expired"
wget -O edit_dropbear "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/edit_dropbear"
wget -O edit_openssh "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/edit_openssh"
wget -O edit_openvpn "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/edit_openvpn"
wget -O edit_ports "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/edit_ports"
wget -O edit_squid3 "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/edit_squid3"
wget -O edit_stunnel4 "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/edit_stunnel4"
wget -O menu "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/menu"
wget -O options "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/options"
wget -O ram "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/ram"
wget -O reboot_sys "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/reboot_sys"
wget -O reboot_sys_auto "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/reboot_sys_auto"
wget -O renew_account "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/renew_account"
wget -O restart_services "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/restart_services"
wget -O set_multilogin_autokill "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/set_multilogin_autokill"
wget -O set_multilogin_autokill_lib "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/set_multilogin_autokill_lib"
wget -O show_ports "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/show_ports"
wget -O user_delete "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/user_delete"
wget -O user_list "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/user_list"
wget -O update "https://github.com/praiman99/AutoScriptVPN/raw/master/Files/Menu/update"
chmod +x bench-network
chmod +x connections
chmod +x create
chmod +x create_trial
chmod +x delete_expired
chmod +x edit_dropbear
chmod +x edit_openssh
chmod +x edit_openvpn
chmod +x edit_ports
chmod +x edit_squid3
chmod +x edit_stunnel4
chmod +x menu
chmod +x options
chmod +x ram
chmod +x reboot_sys
chmod +x reboot_sys_auto
chmod +x renew_account
chmod +x restart_services
chmod +x set_multilogin_autokill
chmod +x set_multilogin_autokill_lib
chmod +x user_delete
chmod +x user_list
chmod +x update
echo "10 0 * * * root clear-log && reboot" >> /etc/crontab
cd
echo "1.5" > /home/ver
clear
echo -e "\e[0;37m  Fix minor Bugs"
echo ""
sleep 0.5
echo -e "\e[0;37m  Thanks for using our script"
echo ""
sleep 0.5
echo -e "\e[0;37m  Server will be reboot In 5 Sec"
sleep 5
rm -f update
reboot
