#!/bin/bash
#Licensed to https://www.hostingtermurah.net/
#Script by PR Aiman

red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to Server..."
sleep 0.5
echo "Checking Permision..."
sleep 0.4
CEK=PRAiman
if [ "$CEK" != "PRAiman" ]; then
		echo -e "${red}Permission Denied!${NC}";
        echo $CEK;
        exit 0;
else
echo -e "${green}Permission Accepted...${NC}"
sleep 1
clear
fi

chmod +x /var/lib/premium-script/data-user-pptp


read -p "Insert Username : " username
grep -E "^$username" /var/lib/premium-script/data-user-pptp >/dev/null
if [ $? -eq 0 ]; then
userpass=`cat /var/lib/premium-script/data-user-pptp | grep "^$username" | awk '{print $3}'`
saat_expired=`cat /var/lib/premium-script/data-user-pptp | grep "^$username" | awk '{print $5}'`
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')
clear
  echo " "
  echo " "
  echo "-----------------------------------------"
  echo " Account Details For Username $Username  "
  echo "-----------------------------------------"
  echo "   Username        : $username"
  echo "   Password        : $userpass"
  echo "   Date Expired    : $tanggal_expired_display"
  echo "-----------------------------------------"
else
echo "Username not found on your server"
    exit 1
fi